name: ssi-project

contracts_folder: contracts

plugins:
  - name: vyper

default_ecosystem: ethereum

networks:
  ethereum:
    local:
      default_provider: http
    sepolia:
      default_provider: infura
